Import buildsystem rework

diff --git a/.github/workflows/build-preview.yaml b/.github/workflows/build-preview.yaml
--- a/.github/workflows/build-preview.yaml
+++ b/.github/workflows/build-preview.yaml
@@ -1,66 +1,356 @@
-name: Test and build preview packages
+#####################################################################
+# Description:  debian-builder-workflow.yaml
+#
+#               This file, 'debian-builder-workflow.yaml', implements
+#               the builder/tester CI/CD workflow for Debian based
+#               systems.
+#
+# Copyright (C) 2020       Jakub Fišer <jakub DOT fiser AT eryaf DOT com>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU Lesser General Public
+# License as published by the Free Software Foundation; either
+# version 2.1 of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+# Lesser General Public License for more details.
+#
+# You should have received a copy of the GNU Lesser General Public
+# License along with this library; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
+#
+######################################################################
+
+name: Test application and publish packages (Debian linux)
 
 on:
   push:
     branches:
-      - '*'
+    - '*'
+    tags-ignore:
+    - 'v*'
+
   pull_request:
     branches:
-    - 'master'
+    - '*'
+
+env:
+  ImageNameRoot: 'machinekit-hal-debian-builder-v'
 
 jobs:
-  testMachinekitHAL:
+  prepareState:
     runs-on: ubuntu-latest
-    env:
-      IMAGE: 'eryaf/mk-cross-builder'
-    strategy:
-      matrix:
-        image_tag: [amd64_8, amd64_9, amd64_10]
+    outputs:
+      BuildDockerImages: ${{ env.BuildDockerImage }}
+      HasCloudsmithToken: ${{ steps.cloudsmith_checker.outputs.tokenPresent }}
+      HasSigningKey: ${{ steps.signing_key_checker.outputs.keyPresent }}
 
     steps:
-    - name: Clone this repository
+    - name: Show GitHub context as a JSON
+      run: |
+        echo "$GITHUB_CONTEXT"
+      env:
+        GITHUB_CONTEXT: ${{ toJson(github) }}
+
+      # Fetch the whole history here as there is no way of knowing how many commits there were in push event
+    - name: Deep clone Machinekit-HAL repository
       uses: actions/checkout@v2
       with:
-        ref: ${{ github.event.sha }}
-        path: to_build
-
-    - name: Test Machinekit code on AMD64
-      run: scripts/build_docker -i ${{ env.IMAGE }} -t ${{ matrix.image_tag }} -c test
-      working-directory: ./to_build
-
-  buildMachinekitHALPackages:
-    runs-on: ubuntu-latest
-    env:
-      IMAGE: 'eryaf/mk-cross-builder'
-    strategy:
-      matrix:
-        # Jessie does not have a ARM64 build
-        image_tag: [amd64_8, amd64_9, amd64_10, arm64_9, arm64_10, armhf_8, armhf_9, armhf_10, i386_8, i386_9, i386_10]
-
-    steps:
-    - name: Clone this repository
-      uses: actions/checkout@v2
-      with:
-        ref: ${{ github.event.sha }}
-        path: to_build/mkhal
-
-    - name: Build Machinekit-HAL .deb package
-      run: scripts/build_docker -i ${{ env.IMAGE }} -t ${{ matrix.image_tag }} -c deb
-      working-directory: ./to_build/mkhal
-
-    - name: Print built files
-      run: find . -depth -not \( -path "." -or -path "./mkhal" -or -path "./mkhal/*" \) -print0 | xargs -0 -I '{}' ls --color -d '{}'
-      working-directory: ./to_build
-
-    - name: Create output directory 
-      run: mkdir ./machinekit-hal-debian
+        ref: '${{ github.event.ref }}'
+        fetch-depth: '0'
+        path: 'machinekit-hal'
     
-    - name: Copy built files into output directory
-      run: find ./to_build -depth -not \( -path "." -or -path "./to_build" -or -path "./to_build/mkhal" -or -path "./to_build/mkhal/*" \) -print0 | xargs -0 -t -I '{}' cp -v '{}' ./machinekit-hal-debian
+    - name: DEBUG, delete
+      run: |
+        git log --oneline
+      working-directory: ./machinekit-hal
+    
+    - name: Get SHAs needed for file changes checking
+      id: event_normalizer 
+      run: |
+        if [ "${{ github.event_name }}" == "push" ]; then
+          echo "::set-output name=before::${{ github.event.before }}"
+          echo "::set-output name=after::${{ github.sha }}"
+          exit 0
+        fi
+        if [ "${{ github.event_name }}" == "pull_request" ]; then
+          echo "::set-output name=before::${{ github.event.base.sha }}"
+          echo "::set-output name=after::${{ github.sha }}"
+          exit 1
+        fi
+        printl "Disallowed event type\n"
+        exit 1
 
-    - name: Upload the built artifacts
-      uses: actions/upload-artifact@v1
+    - name: Check if Docker images related files were changed in this event
+      run: |
+        if [[ ${BEFORE} =~ ^0+$ ]]; then
+          printf "This is new branch\n"
+          exit 0
+        fi
+        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${BEFORE} ${AFTER})
+        printf "Found changed files in this event:\n$CHANGED_FILES\n====\n"
+        while IFS= read -r line; do
+          if [[ $line =~ $DOCKER_REGEX ]]; then 
+            printf "Found file $line matching the regular expression for Debian builder files\n"
+            echo "::set-env name=BuildDockerImage::true"
+            exit 0
+          fi
+        done <<< "$CHANGED_FILES"
+        printf "No changes in Debian builder files were found, not going to force rebuild\n"
+      env:
+        BEFORE: ${{ steps.event_normalizer.outputs.before }}
+        AFTER: ${{ steps.event_normalizer.outputs.after }}
+        DOCKER_REGEX: '^scripts/(((containers/){0,1}buildsystem/debian/.{1,})|build_debian_docker_image)$'
+      working-directory: ./machinekit-hal
+
+    - name: Check on which architecture the workflow is running on
+      id: runtime_architecture
+      run: |
+        ARCHITECTURE=$(uname --machine)
+        RENAMEARCH=""
+        case "$ARCHITECTURE" in
+          "x86_64")
+            RENAMEARCH="amd64"
+            ;;
+          *)
+            echo "Architecture $ARCHITECTURE is unrecognized"
+            exit 1
+            ;;
+        esac
+        echo "This job is going to use $RENAMEARCH as an achitecture tag"
+
+    - name: Build a GraphQL query for questioning Github Packages Docker registry
+      if: env.BuildDockerImage != 'true'
+      run: |
+        echo "
+          query: 
+            'query(\$owner: String!, \$repository: String!, \$inquiry: String!) {
+              repository(owner: \$owner, name: \$repository) {
+                registryPackagesForQuery(packageType: DOCKER, first: 100, query: \$inquiry) {
+                  nodes {
+                    name
+                    version(version: \"latest\") {
+                      platform
+                      sha256
+                    }
+                  }
+                }
+              }
+            }'
+          variables:
+            owner:
+              type: arg
+              name: owner
+            repository:
+              type: arg
+              name: repository
+            inquiry:
+              type: arg
+              name: inquiry
+        " > DockerImagesInGithubPackagesQuery.yaml
+
+    - name: Query GitHub Packages registry for Docker images
+      if: env.BuildDockerImage != 'true'
+      uses: helaili/github-graphql-action@2.0.1
+      id: get_debian_builders_data
       with:
-        name: machinekit-hal-debian-${{ matrix.image_tag }}-${{ github.sha}}
-        path: machinekit-hal-debian
-       
+        query: DockerImagesInGithubPackagesQuery.yaml
+        outputFile: DockerImagesInGithubPackagesResponse.json
+        logLevel: debug
+        owner: ${{ github.event.repository.owner.name }}
+        repository: ${{ github.event.repository.name }}
+        inquiry: 'is:public ${{ env.ImageNameRoot }}'
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Check if all Debian builder Docker images are present
+      if: env.BuildDockerImage != 'true'
+      run: |
+        test_array=(${IMAGE_SUFFIX_ARRAY})
+        MISSING=0
+        for i in ${test_array[@]}
+        do
+          IMAGENAME="${IMAGE_NAME_ROOT}$i"
+          IMAGESHA=$(printl "${INPUT_JSON}" | jq -r --arg IMAGENAME "$IMAGENAME" '.data.repository.registryPackagesForQuery.nodes[] | select(.name == $IMAGENAME).version.sha256')
+          if [ -z "$IMAGESHA" ]; then
+            printf "Docker image $IMAGENAME:latest does not exist in registry docker.pkg.github.com/$REPOSITORY\n"
+            ((MISSING=MISSING+1))
+          fi
+        done
+        if [ $MISSING -gt 0 ]; then
+          printf "There is $MISSING Docker images\n"
+          echo ::set-env name=BuildDockerImage::true
+        fi
+      env:
+        IMAGE_SUFFIX_ARRAY: 'amd64_8 amd64_9 amd64_10 arm64_9 arm64_10 i386_8 i386_9 i386_10 armhf_8 armhf_9 armhf_10'
+        IMAGE_NAME_ROOT: ${{ env.ImageNameRoot }}
+        REPOSITORY: ${{ github.repository }}
+        INPUT_JSON_FILE: 'DockerImagesInGithubPackagesResponse.json'
+    
+    - name: Check if Cloudsmith authorization token is present in GitHub secrets storage
+      id: cloudsmith_checker
+      run: |
+        if ! [ -z "$CLOUDSMITH_TOKEN" ]; then
+          printf "Cloudsmith.io authorization token found in GitHub secret storage, will try to upload\n"
+          echo "::set-output name=tokenPresent::true"
+        else
+           printf "Cloudsmith.io authorization token not found in GitHub secret storage\n"
+          echo "::set-output name=tokenPresent::false"
+        fi
+      env:
+        CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
+
+    - name: Check if signing key is present in GitHub secrets storage
+      id: signing_key_checker
+      run: |
+        if ! [ -z "$SIGNING_KEY" ]; then
+          printf "Signing key found in GitHub secret storage, will try to sign\n"
+          echo "::set-output name=keyPresent::true"
+        else
+           printf "Signing key not found in GitHub secret storage\n"
+          echo "::set-output name=keyPresent::false"
+        fi
+      env:
+        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
+  
+  buildMachinekitHALDebianPackages:
+    runs-on: ubuntu-latest
+    needs: prepareState
+    strategy:
+      matrix:
+        osVersion: ['jessie', 'stretch', 'buster', 'bullseye']
+        architecture: ['i386', 'amd64', 'armhf', 'arm64']
+        exclude:
+          - osVersion: 'jessie'
+            architecture: 'arm64'
+      fail-fast: false
+    
+    steps:
+      - name: Clone Machinekit-HAL repository
+        uses: actions/checkout@v2
+        with:
+          ref: '${{ github.event.ref }}'
+          path: 'build/machinekit-hal'
+      
+      - name: Prepare Machinekit-HAL Debian builder Docker image suffix
+        id: tag_normalizer
+        run: |
+          VER=""
+          case "${{ matrix.osVersion }}" in
+            "jessie")
+              VER="8"
+              ;;
+            "stretch")
+              VER="9"
+              ;;
+            "buster")
+              VER="10"
+              ;;
+            "bullseye")
+              VER="11"
+              ;;
+          esac
+          TAG="${{ matrix.architecture }}_$VER"
+          printf "Tag for this job is $TAG\n"
+          echo "::set-output name=tag::${TAG}"
+
+      - name: Prepare the Docker image
+        run: |
+          if [ "${{ needs.prepareState.outputs.BuildDockerImages }}" == "true" ]; then
+          scripts/build_debian_docker_image -r temp -i temp -t ${TAG}
+          docker tag temp/temp:${TAG} ${IMAGE_NAME_ROOT}${TAG}:latest
+          exit 0
+          fi
+          printf "${{ env.GITHUB_TOKEN}}" | docker login docker.pkg.github.com -u $GITHUB_OWNER --password-stdin
+          docker pull ${IMAGE_NAME_ROOT}${TAG}:latest
+          docker tag ${IMAGE_NAME_ROOT}${TAG}:latest temp/temp:${TAG}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          IMAGE_NAME_ROOT: ${{ env.ImageNameRoot }}
+          GITHUB_OWNER: ${{ github.event.repository.owner.name }}
+          TAG: ${{ steps.tag_normalizer.outputs.tag }}
+        working-directory: ./build/machinekit-hal
+
+      - name: Build Machinekit-HAL debian package
+        run: |
+          scripts/build_docker -i $DOCKER_IMAGE -t $TAG -c deb -n
+        env:
+          TAG: ${{ steps.tag_normalizer.outputs.tag }}
+          DOCKER_IMAGE: 'temp/temp:${{ steps.tag_normalizer.outputs.tag }}'
+        working-directory: ./build/machinekit-hal  
+
+      - name: Sign the package with Machinekit Builder Signer Key
+        run: echo "AHOJ"
+
+      - name: Upload built package for Debian ${{ matrix.osVersion}}, ${{ matrix.architecture }} as an artifact
+        run: echo "AHOJ"
+
+  testMachinekitHALBuild:
+    runs-on: ubuntu-latest
+    needs: prepareState
+    strategy:
+      matrix:
+        osVersion: ['jessie', 'stretch', 'buster', 'bullseye']
+      fail-fast: false
+
+    steps:
+      - name: Clone Machinekit-HAL repository
+        run: echo "AHOJ"
+
+      - name: Prepare Docker image
+        run: echo "AHOJ"
+
+      - name: Build Machinekit-HAL Run-In-Place
+        run: echo "AHOJ"
+
+      - name: Execute Runtests
+        run: echo "AHOJ"
+
+      - name: Execute CMOCKA UNIT tests
+        run: echo "AHOJ"
+
+      - name: Execute Python nosetests
+        run: echo "AHOJ"
+
+  buildContainerImagesForUpload:
+    runs-on: ubuntu-latest
+    if: needs.prepareState.outputs.BuildDockerImages == 'true'
+    needs: [buildMachinekitHALDebianPackages, testMachinekitHALBuild, prepareState]
+    strategy:
+      matrix:
+        osVersion: ['jessie', 'stretch', 'buster', 'bullseye']
+        architecture: ['i386', 'amd64', 'armhf', 'arm64']
+        exclude:
+          - osVersion: 'jessie'
+            architecture: 'arm64'
+      fail-fast: false
+    
+    steps:
+      - name: Download settings file from GitHub storage
+        run: echo "AHOJ"
+
+      - name: Clone Machinekit-HAL repository
+        run: echo "AHOJ"
+
+      - name: Build the docker image for ${{ matrix.osVersion}}, ${{ matrix.architecture }} Builder
+        run: echo "AHOJ"
+
+      - name: Upload the container image to repository's Github Packages registry
+        run: echo "AHOJ"
+
+      - name: Do the QUAY thing
+        run: echo "AHOJ"
+
+  uploadMachinekitHALDebianPackages:
+    runs-on: ubuntu-latest
+    if: needs.prepareState.outputs.HasCloudsmithToken == 'true'
+    needs: [buildContainerImagesForUpload, prepareState]
+    
+    steps:
+      - name: Download built artifacts from GitHub storage
+        run: echo "AHOJ"
+
+      - name: Upload the Debian packages to Cloudsmith hosting service
+        run: echo "AHOJ"
